# fly.toml app configuration file generated for meal-optimization-assistant on 2025-06-08T22:17:49+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'meal-optimization-assistant'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'data'
  destination = '/app/data'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
